const education = [
    {
        courseId: 1,
        name: 'BA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/teacher-tablet-students-adult-education-class-71527448.jpg',
    },
    {
        courseId: 2,
        name: 'BBA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/mature-students-sitting-desks-adult-education-class-mature-students-sitting-desks-adult-education-class-104867510.jpg',
    },
    {
        courseId: 3,
        name: 'Bsc',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/male-teacher-using-tablet-computer-adult-education-class-71524313.jpg',
    },
    {
        courseId: 4,
        name: 'MBA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/education-high-school-university-learning-people-concept-smiling-student-girl-reading-book-education-high-school-university-172068379.jpg',
    },
    {
        courseId: 5,
        name: 'MA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/asian-college-student-21123766.jpg',
    },
    {
        courseId: 6,
        name: 'CA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/asian-college-student-19816185.jpg',
    },
    {
        courseId: 7,
        name: 'FCA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/z/portrait-college-student-24706420.jpg',
    },
    {
        courseId: 8,
        name: 'Bcom',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/male-college-student-29017516.jpg',
    },
    {
        courseId: 9,
        name: 'BCA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/hispanic-college-student-26145883.jpg',
    },
    {
        courseId: 10,
        name: 'LLB',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/male-college-student-university-lecture-hall-5949213.jpg',
    },
    {
        courseId: 11,
        name: 'BE',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/male-college-friends-campus-5949387.jpg',
    },
    {
        courseId: 12,
        name: 'BTech',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/group-university-students-working-library-4979899.jpg',
    },
    {
        courseId: 13,
        name: 'MDA',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/male-college-student-university-lecture-hall-5949112.jpg',
    },
    {
        courseId: 14,
        name: 'BED',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/group-college-students-leaning-banister-5949686.jpg',
    },
    {
        courseId: 15,
        name: 'FM',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/young-man-using-laptop-campus-lawn-5949845.jpg',
    },
    {
        courseId: 16,
        name: 'EBE',
        price: 21,
        img: 'https://thumbs.dreamstime.com/b/high-school-tablet-computer-27208247.jpg',
    },
]